version: '3.8'
services:
  client:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/client-mentoryard
    working_dir: /client-mentoryard
    image: app:client-mentoryard
    container_name: mentoryard_container
    command: npm start
